### ISSUE TITLE
TEEApps和capsule-manager之间的远程认证

### ISSUE THREAD

**Issue by PrimumMobile** [asterinas/trustflow-capsule-manager#19]
![image](https://github.com/secretflow/capsule-manager/assets/120082883/b08716e9-5f23-454b-9c08-c2a39b40ecd8)
左侧是capsule-manager提供的grpc服务，右侧是TEEApps调用的部分。TEEApps生成ResultDataKey给到capsule-manager保存，这个过程不应该是TEEApps远程认证capsule-manager吗？看代码里面的Log怎么是TEEApps在生成attestation_report啊？

**Comment by zhongtianq** [comment]
创建ResultDataKey的步骤中会有权限的继承关系，所以不是任何应用都可以向capsule manager注册结果密钥，只有具备源数据访问权限的teeapps才能注册计算结果的数据密钥。因此这边是capsule manager认证teeapps的attestation_report

**Comment by PrimumMobile** [comment]
> 创建ResultDataKey的步骤中会有权限的继承关系，所以不是任何应用都可以向capsule manager注册结果密钥，只有具备源数据访问权限的teeapps才能注册计算结果的数据密钥。因此这边是capsule manager认证teeapps的attestation_report

如果不对capsule manager进行认证，那没有办法保证ResultDataKey保存在了可信的capsule manager中，不会有问题吗
